export const RESUME = {
  DELETE: 'RESUME_DELETE',
  LIST: 'RESUME_LIST',
  DETAIL: 'RESUME_DETAIL',
  INSERT: 'RESUME_INSERT',
  UPDATE: 'RESUME_UPDATE',
  UPSERT: 'RESUME_UPSERT'
}

export const MESSAGE = {
  DELETE: 'MESSAGE_DELETE',
  LIST: 'MESSAGE_LIST',
  DETAIL: 'MESSAGE_DETAIL',
  INSERT: 'MESSAGE_INSERT',
  UPDATE: 'MESSAGE_UPDATE',
  UPSERT: 'MESSAGE_UPSERT'
}
