export const RESUME = {
  DELETE: 'RESUME_DELETE',
  LIST: 'RESUME_LIST',
  DETAIL: 'RESUME_DETAIL',
  INSERT: 'RESUME_INSERT',
  UPDATE: 'RESUME_UPDATE',
  UPSERT: 'RESUME_UPSERT'
}

export const CONTACT_MESSAGE = {
  DELETE: 'CONTACT_MESSAGE_DELETE',
  LIST: 'CONTACT_MESSAGE_LIST',
  DETAIL: 'CONTACT_MESSAGE_DETAIL',
  INSERT: 'CONTACT_MESSAGE_INSERT',
  UPDATE: 'CONTACT_MESSAGE_UPDATE',
  UPSERT: 'CONTACT_MESSAGE_UPSERT'
}
